-   id: imageoptim
    name: imageoptim
    entry: bash -c 'echo "$@" | xargs -n1 | imageOptim --quit --no-color  --image-alpha' --
    language: node
    files: \.(png|jpeg|jpg|gif)$
    description: An hook to run image-optimin, jpegmin to optimise images
    args: []

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.7.0
